# Configuration for Cloudflare Pages
name = "mira-booking"
pages_build_output_dir = "./out"

# Environment variables (if needed for build)
[vars]
ENVIRONMENT = "production"
DEPLOY_TIME = "real-time"
JWT_SECRET = "" 